### ISSUE TITLE
Backup location disabled after backup failed on re-formated flash drive

### ISSUE THREAD

**Issue by An-anonymous-coder** [stevesoltys/backup#805]
After GrapheneOS updated Seedvault in their [latest release](https://grapheneos.org/releases#2024112700), I'm running into an issue. I'm going to give a rough outline of what may have caused it:

1. Format a new USB drive for Android storage. The name of it is "android", I don't know if there is a way to change this.
2. Using the old version of Seedvault, create a backup location inside the drive
3. Backup like normal
4. Eject the drive
5. Update Seedvault to the new version
6. Insert the USB drive
7. Format the USB drive. This will wipe the Seedvault data and the device will be named "android" still.
8. Open Seedvault

You will receive a notification "**Backup failed:** An error occurred while running the backup"

The option to select the backup location is grayed out, even when the USB drive is not plugged in.

Backup scheduling is set to 1 week. Backup status says "Last backup: Never", even though it has been backed up recently. 

I essentially have no way to backup to this USB drive now, or anywhere else since I can't change the backup location. 

```
version 15-5.1
versionCode 35050010
Android 15: GrapheneOS 2024112700
```

**Comment by An-anonymous-coder** [comment]
I like to frequently format the USB drive for backup sanity and cleanliness, especially after major updates like this.

**Comment by An-anonymous-coder** [comment]
I tried formatting the drive off-device and naming it something other than "android". Same error message, still no way to change backup location. 

Should I clear Seedvault's cache and storage?

**Comment by grote** [comment]
Can you reproduce the issue using steps 6 to 8 only? I just want to be sure that the upgrade to the new version is not involved here.

Otherwise, frequently reformatted the backup medium isn't something we really tested so far.

> Should I clear Seedvault's cache and storage?

Yes, if there's no data to lose, you can do that, also to get back to a working state to reproduce 6-8 above.

If you can reproduce, and after formatting, backup fails and you can't change storage location, then please export logs from expert settings and post them here. Thanks.

**Comment by An-anonymous-coder** [comment]
I cleared cache and storage and I was able to backup as normal.

Repeating steps 6-8 reproduced the bug. I didn't receive an error notification. It says the last backup was (correctly) 5 minutes ago. Here is a revised bug report:

1. Format a new USB drive for Android storage. The name of it is "android", I don't know if there is a way to change this.
2. Create a backup location inside the drive
3. Backup like normal.
After the backup is finished, you may eject and reinstert the flash drive, if desired. This isn't necessary. 
4. Format the USB drive. This will wipe the Seedvault data and the device will be named "android" still.
5. Open Seedvault

You will not be able to select a backup location or create a backup. 

[seedvault-15-5.1-1732926357439.txt](https://github.com/user-attachments/files/17963619/seedvault-15-5.1-1732926357439.txt)

There may be some oddities around the log, if that is the case I will explain why it may have occurred and will try to provide better logs. If there are no oddities, disregard this.

**Comment by lxto** [comment]
Same issue on my Pixel7a , GOS Built 2024120200. 
Additional advice: I am using 2 different USB-C drives alternating, which worked well in earlier versions. Now only the latest USB-C drive used for backup allows further backups (not greyed out). After plugging in the altenate drive , the backup target is greyed. However when inserting the latest used backup-Drive it is possible to change the backup-target to e.g. "device" or "nextcloud" or "dav-device". I see this behaviour no matter if the backup failed or succeded.

**Comment by grote** [comment]
> After plugging in the altenate drive , the backup target is greyed.

Sounds like there's a bug and it may indeed be the same one as the reformated drive. @t-m-w can you reproduce?

**Comment by t-m-w** [comment]
> Sounds like there's a bug and it may indeed be the same one as the reformated drive. @t-m-w can you reproduce?

Yes. I accidentally tried these steps with 15.5-0 at first, and everything was fine. As soon as I updated to 15.5-1, "Backup location" became grayed out for the first time in testing.

**Comment by jkos95** [comment]
I am also experiencing this issue. Only the last working flash drive works. I have formatted and tried another but backup location is greyed out. 

I have a pixel 6 on Android 15 2024120400.

**Comment by jkos95** [comment]
> I tested after you merge and it is working successfully. At first, the backup location was still greyed out, so I plugged in my original flash drive that was working, and when the backup location lit up, I switched to internal storage. After that I unmounted and plugged in my new one (mSATA to USB enclosure) and I was able to select it and backup no problem. 

Edit: I spoke too soon. The backup failed since it did not like using the mSATA drive after a few minutes. I tried a flash drive after formatting my original one and now cannot get anything to un-grey the backup location :(

**Comment by nobody77777** [comment]
I have the same issue after re-formatting the USB drive. Effectively backup is no longer possible. Is there any workaround to force-forget the old backup location?

Pixel 8A
Android 15
Build 2024121200

**Comment by grote** [comment]
What Seedvault version are you on? Issue should be fixed in `14-5.2` and `15-5.2`.

**Comment by nobody77777** [comment]
Ah perfect. I have 15-5.1 at this time with GrapheneOS. Hopefully the 15-5.2 gets bundled with the next update.
Thank you

**Comment by jkos95** [comment]
I just updated everything and rebooted and the issue persists for me :(

Build # 2024123000
Kernal 5.10.232-android...

**Comment by grote** [comment]
@jkos95 I don't know what `Build # 2024123000` is. What ROM are you on and what version of Seedvault is shown in its About screen?

**Comment by jkos95** [comment]
> @jkos95 I don't know what `Build # 2024123000` is. What ROM are you on and what version of Seedvault is shown in its About screen?

ROM: 2025010700
Seedvault version: 15-5.1

**Comment by grote** [comment]
Thanks! I still don't know what ROM this is, but the fix is only on 15-5.2, so you need to wait until your ROM updates Seedvault or do it yourself, if you self-build your ROM.

**Comment by jkos95** [comment]
> Thanks! I still don't know what ROM this is, but the fix is only on 15-5.2, so you need to wait until your ROM updates Seedvault or do it yourself, if you self-build your ROM.

I appreciate the info. I'll watch for that update!

**Comment by An-anonymous-coder** [comment]
An up to date version of Seedvault will now be packaged with the next GrapheneOS update.

**Comment by An-anonymous-coder** [comment]
GrapheneOS [2025011500](https://grapheneos.org/releases#2025011500) released for the **Alpha** channel at 00:00 UTC today, which packaged an updated version of Seedvault (`15-5.2`). Any users still experiencing this issue or potentially related issues on GrapheneOS should update to 2025011500 first to see if the issue persists. 2025011500 should reach **Beta** and **Stable** channels soon.

**Comment by nobody77777** [comment]
Working like a charm. Thank you!

**Comment by jkos95** [comment]
Confirmed, build 2025011500 was pushed to stable 5 days ago and I updated. The seed vault backup worked great without issue right after. 

Thanks all and nice work!
